spring.application.name=Turistik_Explorer
# Configuracion de la base de datos (conexion a Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/turismo_db
spring.datasource.username=postgres
spring.datasource.password=admin123



spring.jpa.show-sql=true

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.continue-on-error=false

# Configuracion de seguridad basica
spring.security.user.name=admin
spring.security.user.password=admin123

# Configuracion de API Externa
api.weather.key=ea38bd191dbfcd43da3bad4fd363c56d

server.port=8081

spring.thymeleaf.cache=false
spring.docker.compose.enabled=false